{
 "title": "MikroTik CHR - Multi-Cloud Network Weathermap",
 "tags": [
  "mikrotik",
  "chr",
  "network",
  "weathermap",
  "topology"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Router Instance",
    "query": {
     "query": "query_result(up{job=\"snmp-chr\", instance=~\"chr-.*-.*\"} == 1)"
    }
   },
   {
    "name": "interface",
    "label": "GRE Tunnel Interface",
    "query": {
     "query": "label_values(ifHCInOctets{instance=\"$instance\", ifName!=\"lo\"}, ifName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Multi-Cloud Network Weathermap",
   "type": "canvas",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-gcp-jkt\", ifName=\"gre-ali\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-gcp-jkt\", ifName=\"gre-ali\"}[1m]) * 8)",
     "legendFormat": "GCP <-> Aliyun"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-gcp-jkt\", ifName=\"gre-azure\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-gcp-jkt\", ifName=\"gre-azure\"}[1m]) * 8)",
     "legendFormat": "GCP <-> Azure"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-gcp-jkt\", ifName=\"gre-aws\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-gcp-jkt\", ifName=\"gre-aws\"}[1m]) * 8)",
     "legendFormat": "GCP <-> AWS SG"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-azure-jkt\", ifName=\"gre-ali\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-azure-jkt\", ifName=\"gre-ali\"}[1m]) * 8)",
     "legendFormat": "Aliyun <-> Azure"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-aws-sg\", ifName=\"gre-ali\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-aws-sg\", ifName=\"gre-ali\"}[1m]) * 8)",
     "legendFormat": "Aliyun <-> AWS SG"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-azure-jkt\", ifName=\"gre-aws\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-azure-jkt\", ifName=\"gre-aws\"}[1m]) * 8)",
     "legendFormat": "Azure <-> AWS SG"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-aws-jkt\", ifName=\"gre-azure\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-aws-jkt\", ifName=\"gre-azure\"}[1m]) * 8)",
     "legendFormat": "Azure <-> AWS JKT"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=~\"chr-aliyun-nextops|chr-aliyun-jkt\", ifName=\"gre-ms\"}[1m]) * 8 or rate(ifHCOutOctets{instance=~\"chr-aliyun-nextops|chr-aliyun-jkt\", ifName=\"gre-ms\"}[1m]) * 8)",
     "legendFormat": "Aliyun NextOps <-> Aliyun MS"
    },
    {
     "expr": "max(rate(ifHCInOctets{instance=\"chr-aws-jkt\", ifName=\"gre-aliyun\"}[1m]) * 8 or rate(ifHCOutOctets{instance=\"chr-aws-jkt\", ifName=\"gre-aliyun\"}[1m]) * 8)",
     "legendFormat": "Aliyun NextOps <-> AWS JKT"
    }
   ]
  },
  {
   "title": "Tunnel Inbound Bandwidth Rate (Download) - $instance [$interface]",
   "type": "timeseries",
   "description": "Real-time download rate for the selected GRE tunnel.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"$instance\", ifName=\"$interface\"}[1m]) * 8",
     "legendFormat": "{{instance}} [{{ifName}}] Inbound"
    }
   ]
  },
  {
   "title": "Tunnel Outbound Bandwidth Rate (Upload) - $instance [$interface]",
   "type": "timeseries",
   "description": "Real-time upload rate for the selected GRE tunnel.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{instance=\"$instance\", ifName=\"$interface\"}[1m]) * 8",
     "legendFormat": "{{instance}} [{{ifName}}] Outbound"
    }
   ]
  }
 ]
}